Add stbt.enable_caching API
stb-tester/stb-tester pull request #697
Opened 2020-09-26 15:34 UTC by drothlis

We already have a way of caching image-processing operations (such as `match` and `ocr`) but we can either cache them all or not at all. This allows you to selectively enable the cache at run-time for *some* ocr operations.

TODO:

- [ ] Decide on the API.
- [ ] Tests.

2020-09-26 15:41 UTC, drothlis commented
@wmanley please review the API.

- In the first commit I added the `stbt.enable_caching()` contextmanager.

- In the second commit I simplified the implementation by breaking backwards compatibility of the `imgproc_cache` API. This was always a private API so I think it's worth it.

- In the last commit I added a `cache=<bool>` parameter to `stbt.ocr()`. I'm not so sure about this one, might drop it. I expect the caching to be useful in a very limited set of cases, so it doesn't matter if it's a bit more verbose. In those cases you would do this:

  ```
  with stbt.enable_caching():
      return stbt.ocr(self._frame, region=...)
  ```

2020-09-28 09:48 UTC, drothlis commented
From discussion with @wmanley:

* Enable ocr caching by default. This would allow us to use OCR more freely for menu navigation, in `wait_until` loops, etc.

2020-09-28 11:35 UTC, drothlis commented
Open questions:

- [ ] Should we remove stbt.ocr's `cache` parameter? (And leave it so that it's always caching.) I'd rather not have a parameter that's there "just in case", is never used, but we have to continue to support & document it. Another disadvantage is that `cache=False` will apply to the Object Repository too, where we *know* it's safe to use.
- [ ] Should we add caching to `match_text` too?
- [ ] Should we remove the `with stbt.enable_caching()` public API I've added? I don't know any compelling use-cases apart from ocr.
- [ ] Regarding the implementation: Maybe instead of the extra `enable_caching` contextmanager, the `memoize` decorator could inspect the arguments to see if one of them is called `cache`, and if False, disable the caching?

2020-09-29 11:13 UTC, drothlis commented
Rebased onto master and squashed away intermediate commits where I changed my mind multiple times -- to make reviewing easier.

2020-09-29 15:13 UTC, wmanley requested changes

2020-09-29 23:05 UTC, drothlis commented on _stbt/imgproc_cache.py
>  def memoize(additional_fields=None):
Huh, the thought of thread safety never even crossed my mind. I have added `use_cache` to the memoized function (`inner`) in 6574bcfc.

2020-09-30 07:41 UTC, merged