wait_until: Add type annotations
stb-tester/stb-tester pull request #760
Opened 2022-06-23 16:55 UTC by drothlis

2022-10-12 14:26 UTC, drothlis commented
It works! Before:

![vscode before](https://user-images.githubusercontent.com/12424/195369734-d58372b5-cf45-4e9f-b8b7-5d8d877796fc.png)

After:

![vscode after](https://user-images.githubusercontent.com/12424/195369772-4b65cd3c-d10c-46a9-8855-94f8db522cf9.png)

2022-10-13 08:31 UTC, wmanley requested changes

2022-10-13 08:31 UTC, wmanley commented on _stbt/wait.py
> +               interval_secs: int = 0,
These should be `float`

```suggestion
               timeout_secs: float = 10,
               interval_secs: float = 0,
```

2022-10-13 08:31 UTC, wmanley commented on _stbt/wait.py
> +               stable_secs: int = 0) -> T | None:
```suggestion
               stable_secs: float = 0) -> T | None:
```

2022-10-13 08:31 UTC, wmanley commented
Very helpful.  I had a branch where I'd annotated all of our types at some point, I'll have to find it.

2022-10-13 08:34 UTC, drothlis commented on _stbt/wait.py
> +               stable_secs: int = 0) -> T | None:
Done.

2022-10-13 08:34 UTC, drothlis commented on _stbt/wait.py
> +               interval_secs: int = 0,
Done.

2022-10-13 08:41 UTC, wmanley approved these changes

2022-10-13 08:41 UTC, merged